# Site
repository: bcapuzzo/bcapuzzo.github.io
# favicon: images/favicon.ico
favicon: images/profile-pic.jpg


# Content configuration version
version: 2

# Personal info
name: Brendan Capuzzo
title: Computer Science Master's Student at Rensselaer Polytechnic Institute
email: bcapuzzo5@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: bcapuzzo5
github_username:  bcapuzzo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: bcap5
linkedin_username: brendan-capuzzo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Merit Pages link
  icon: fas fa-globe
  url: https://meritpages.com/brendan-capuzzo
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Brendan Capuzzo and I am a master's student at Rensselaer Polytechnic Institute (RPI) studying Computer Science with an expected graduation of December 2024. I recently completed my B.S. in Computer & Systems Engineering and Computer Science at RPI in December 2023.
  
  Driven and highly motivated student with an interest in emerging technologies, computer networking, and software. Pursuing a master's degree to further refine my technical expertise and contribute to innovations across the technology industry. Possessing strong programming skills and a collaborative mindset, I am committed to making a positive impact in the field of computer science and actively seeking opportunities to learn and grow in a dynamic and innovative environment. Proven success in multiple software engineering internships through collaboration, coding projects, and organizational skills.Driven and highly motivated student with an interest in emerging technologies, computer networking, and software. Pursuing a master's degree to further refine my technical expertise and contribute to innovations across the technology industry. Possessing strong programming skills and a collaborative mindset, I am committed to making a positive impact in the field of computer science and actively seeking opportunities to learn and grow in a dynamic and innovative environment. Proven success in multiple software engineering internships through collaboration, coding projects, and organizational skills.

  I am most skilled in: <mark>C++</mark> and <mark>Python</mark>.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption:
          June 2024 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Principal Financial Group
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: May 2023 - August 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Executed in an Agile environment with embedded software systems and performed bench testing on processors
          - Utilized object-oriented programming and data structures to implement software designs with UML diagrams
          - Collaborated on a team project which featured the design of a smart home lighting and shading system

      - layout: left
        title: Lutron Electronics
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: September 2022 - December 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Executed in an Agile environment with embedded software systems and performed bench testing on processors
          - Utilized object-oriented programming and data structures to implement software designs with UML diagrams
          - Collaborated on a team project which featured the design of a smart home lighting and shading system

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: Jan 2024 - Dec 2024
        sub_title: M.S. Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Concentration: Artificial Intelligence, Machine Learning, & Data
          - GPA: 3.91
          - Coursework: Cryptography and Network Security, Distributed Systems and Algorithms, Graph Theory

      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: Aug 2020 - Dec 2023
        sub_title: B.S. Computer & Systems Engineering and Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Minor: Economics of Banking and Finance
          - Concentrations: Theory, Algorithms, & Mathematics and Artificial Intelligence & Data
          - GPA: 3.70
          - Accomplishments: *magna cum laude*, Dean's Honor List (7 semesters), RPI Medal Award (June 2019)
          - Coursework: Database Systems, Programming Languages, Design and Analysis of Algorithms, Machine Learning and Optimization, Intro to Artificial Intelligence, Signals and Systems, Intro to Electronics, Operating Systems, Principles of Software, Electric Circuits, Data Structures, Computer Architecture & Networks, Computer Components & Operations, Embedded Control, Intro to Engineering Design, Engineering Communications & CAD, Modeling & Analysis of Uncertainty


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
