# Site
repository: bcapuzzo/bcapuzzo.github.io
favicon: images/profile-pic.jpg

# Content configuration version
version: 2

# Personal info
name: Brendan Capuzzo
title: Computer Science Master's Student at Rensselaer Polytechnic Institute
email: bcapuzzo5@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: brendan-capuzzo
github_username:  bcapuzzo
# instagram_username:
# twitter_username:
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: Merit Pages link
#   icon: fas fa-globe
#   url: https://meritpages.com/brendan-capuzzo
# - title: Download Resume
#   icon: far fa-file-pdf
#   url: /assets/Final Design Poster - Smart Dormitory - Node-RED.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Brendan Capuzzo and I am a software engineer at Microsoft. I recently received my M.S. in Computer Science and B.S. in Computer & Systems Engineering and Computer Science from Rensselaer Polytechnic Institute (RPI).
  
  Driven and highly motivated professional with an interest in emerging technologies, computer networking, and software development. With a master's degree in computer science, I have refined my technical expertise and am passionate about contributing to innovations across the technology industry. Equipped with strong programming skills, a collaborative mindset, and a commitment to continuous learning, I strive to make a positive impact in the field of computer science. I am eager to tackle challenging problems, deliver impactful solutions, and grow in a dynamic and innovative environment.

  I am most skilled in: <mark>C++</mark>, <mark>Swift</mark>, and <mark>Python</mark>.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        link: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started
        link_text: Microsoft Intune App SDK
        sub_title: Software Engineering Intern
        caption:
          Jun 2024 - Aug 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Developed a Swift package for the Intune iOS Mobile Application Management (MAM) SDK
          - Conducted thorough iOS testing of app protection policies to ensure security compliance and multi-library support
          - Integrated Swift packages into build and release pipelines for binary framework distribution to app partners
          - Leveraged Swift Package Manager, Apple Developer Documentation, and Xcode to optimize package dependency

      - layout: left
        title: Principal Financial Group
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: May 2023 - Aug 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Supported the data management team in improving data security through encryption, monitoring, and analysis efforts
          - Applied analytical skills to identify and address vulnerabilities in consumer data practices, ensuring data privacy 
          - Engaged in learning and professional growth by pursuing additional technical experience in Salesforce CRM

      - layout: left
        title: Lutron Electronics
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: Sep 2022 - Dec 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Executed in an Agile environment with embedded software systems and performed bench testing on processors
          - Utilized object-oriented programming and data structures to implement software designs with UML diagrams
          - Collaborated on a team project which featured the design of a smart home lighting and shading system

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: Jan 2024 - Dec 2024
        sub_title: M.S. Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Concentration: Artificial Intelligence, Machine Learning, & Data
          - GPA: 3.95
          - Coursework: Cryptography and Network Security, Distributed Systems and Algorithms, Graph Theory, Data Science, Software Design and Documentation, Mobile AI Explainability, Sense Making and Computation

      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: Aug 2020 - Dec 2023
        sub_title: B.S. Computer & Systems Engineering and Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Minor: Economics of Banking and Finance
          - Concentrations: Theory, Algorithms, & Mathematics and Artificial Intelligence & Data
          - GPA: 3.70
          - Accomplishments: *magna cum laude*, Dean's Honor List (7 semesters), RPI Medal Award (June 2019)
          - Coursework: Database Systems, Programming Languages, Design and Analysis of Algorithms, Machine Learning and Optimization, Intro to Artificial Intelligence, Signals and Systems, Intro to Electronics, Operating Systems, Principles of Software, Electric Circuits, Data Structures, Computer Architecture & Networks, Computer Components & Operations, Embedded Control, Intro to Engineering Design, Engineering Communications & CAD, Modeling & Analysis of Uncertainty
 
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MIT App Inventor Punya AI Explainability
        caption: Jan 2024 - Dec 2024
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Master's Research Project, Dr. Oshani Seneviratne
          - Developed an AI explainability component for Punya, an MIT App Inventor extension
          - Modified the AI reasoner component in Punya to generate human-readable explanations for AI-driven decisions
          - Enhanced AI transparency and trust on mobile platforms by improving the interpretability of AI models, ensuring that non-expert users can easily comprehend, trust, and interact with the AI’s reasoning
          - Collaborated with a team to optimize the responsiveness and user understanding of reasoner outcomes through the evaluation of explainability methodsMaster's Research Project, Dr. Oshani Seneviratne • Developed an AI explainability component for Punya, an MIT App Inventor extension • Modified the AI reasoner component in Punya to generate human-readable explanations for AI-driven decisions • Enhanced AI transparency and trust on mobile platforms by improving the interpretability of AI models, ensuring that non-expert users can easily comprehend, trust, and interact with the AI’s reasoning • Collaborated with a team to optimize the responsiveness and user understanding of reasoner outcomes through the evaluation of explainability methods

      - layout: left
        title: Dinder: Social Restaurant Finder
        link: https://github.com/bcapuzzo/Dinder
        link_text: GitHub Repository
        caption: Sep 2024 - Dec 2024
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Software Design and Documentation, Fall 2024, Professor John Sturman
          - Developed a full-stack web application using the MERN stack (MongoDB, Express, React, Node.js), building a responsive frontend in React for real-time group decision-making on restaurant selectionModified the AI reasoner component in Punya to generate human-readable explanations for AI-driven decisions
          - Integrated Google Places API for restaurant data retrieval with a ranking algorithm that optimizes group preferences for cuisine, price, rating, and location
          - Implemented a swipe-based matching algorithm with WebSocket sessions for live group matching results
          - Led a cross-functional team using Agile methodologies, managing milestones with Jira, version control with GitHub, and deploying a scalable backend on MongoDB

      - layout: left
        title: Smart Dormitory - Node-RED
        caption: Aug 2023 - Dec 2023
        sub_title: Rensselaer Polytechnic Institute
        # link: <a href="assets/Final%20Design%20Poster%20-%20Smart%20Dormitory%20-%20Node-RED.pdf" target="_blank">Download Design Poster</a>
        # link_text: Design Poster
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Multidisciplinary Capstone Design, Fall 2023, Dr. Dennis Shelden
          - Coordinated the enhancement of a low-code Smart Dormitory project which featured an IoT network of ESP32 devices with sensors connected through Arduino IDE and data visualizations powered by Node-RED
          - Integrated JavaScript and SQL to optimize query generation for MySQL database in order to efficiently retrieve historical sensor data and display on a website dashboard through graphs, charts, and heat maps
          - Executed strong project management skills through enhancements and coordinating the team's focus on scalability, energy efficiency, and security for students, building maintenance, and developers
          
          <a href="assets/Final%20Design%20Poster%20-%20Smart%20Dormitory%20-%20Node-RED.pdf" target="_blank" style="color: black">Design Poster</a>

      - layout: left
        title: SMART Pregnancy Band
        caption: Jun 2022 - Aug 2022
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Introduction to Engineering Design, Summer 2022, Dr. George Lee
          - Followed the engineering design process with a team of six students to develop a functional prototype for a SMART Pregnancy Band which featured a back-supporting band with medical sensors and mobile app compatibility
          - Led the team by working on the user interface subsystem by developing a mobile app that was built using MIT App Inventor 2 and intended to be used by pregnant women to track health data and prevent maternal deaths
          - The app featured nine screens with navigation bar and Bluetooth compatibility which was outlined in wireframe flow

      - layout: left
        title: Astro AutoTint
        caption: Jan 2022 - May 2022
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Electric Circuits, Spring 2022, Dr. Shayla Sawyer
          - Developed an Astro AutoTint electric circuit project in a team of three students that used a photoresistor to detect harmful light levels and adjust the shading of an electrochromic glass that could help astronauts in space
          - Utilized LTspice to create circuit schematics and Microsoft Word to develop a project manual demonstrating circuit concepts such as voltage followers, summers, comparators, inverting amplifiers, differentiators, and filters
          - Built and tested physical circuits using a breadboard, wires, operational amplifiers, power lines, and AC power

  - title: Organizations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Theta Xi Fraternity
        caption: Dec 2021 - Dec 2024
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Honors: George M. Baker Memorial Award (Apr 2024)
          - Positions: Facilities Manager (Apr 2024 - Dec 2024), Scholarship Chairman (Apr 2023 - Dec 2023), Vice President / Risk Management Chairman (Dec 2022 - Apr 2023)

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
