# Site
repository: bcapuzzo/bcapuzzo.github.io
# favicon: images/favicon.ico
favicon: images/profile-pic.jpg


# Content configuration version
version: 2

# Personal info
name: Brendan Capuzzo
title: Computer Science Master's Student at Rensselaer Polytechnic Institute
email: bcapuzzo5@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: brendan-capuzzo
github_username:  bcapuzzo
instagram_username: bcap5
twitter_username: bcapuzzo5
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Merit Pages link
  icon: fas fa-globe
  url: https://meritpages.com/brendan-capuzzo
- title: Download Resume
  icon: far fa-file-pdf
  url: /files/Final Design Poster - Smart Dormitory - Node-RED.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Brendan Capuzzo and I am a master's student at Rensselaer Polytechnic Institute (RPI) studying Computer Science with an expected graduation in December 2024. I recently completed my B.S. in Computer & Systems Engineering and Computer Science at RPI in December 2023.
  
  Driven and highly motivated student with an interest in emerging technologies, computer networking, and software. Pursuing a master's degree to further refine my technical expertise and contribute to innovations across the technology industry. Possessing strong programming skills and a collaborative mindset, I am committed to making a positive impact in the field of computer science and actively seeking opportunities to learn and grow in a dynamic and innovative environment. Proven success in multiple software engineering internships through collaboration, coding projects, and organizational skills.
  
  I am most skilled in: <mark>C++</mark> and <mark>Python</mark>.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption:
          Jun 2024 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Principal Financial Group
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: May 2023 - Aug 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Supported the data management team in improving data security through encryption, monitoring, and analysis efforts
          - Applied analytical skills to identify and address vulnerabilities in consumer data practices, ensuring data privacy 
          - Engaged in learning and professional growth by pursuing additional technical experience in Salesforce CRM

      - layout: left
        title: Lutron Electronics
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: Sep 2022 - Dec 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Executed in an Agile environment with embedded software systems and performed bench testing on processors
          - Utilized object-oriented programming and data structures to implement software designs with UML diagrams
          - Collaborated on a team project which featured the design of a smart home lighting and shading system

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: Jan 2024 - Dec 2024
        sub_title: M.S. Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Concentration: Artificial Intelligence, Machine Learning, & Data
          - GPA: 3.91
          - Coursework: Cryptography and Network Security, Distributed Systems and Algorithms, Graph Theory

      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: Aug 2020 - Dec 2023
        sub_title: B.S. Computer & Systems Engineering and Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Minor: Economics of Banking and Finance
          - Concentrations: Theory, Algorithms, & Mathematics and Artificial Intelligence & Data
          - GPA: 3.70
          - Accomplishments: *magna cum laude*, Dean's Honor List (7 semesters), RPI Medal Award (June 2019)
          - Coursework: Database Systems, Programming Languages, Design and Analysis of Algorithms, Machine Learning and Optimization, Intro to Artificial Intelligence, Signals and Systems, Intro to Electronics, Operating Systems, Principles of Software, Electric Circuits, Data Structures, Computer Architecture & Networks, Computer Components & Operations, Embedded Control, Intro to Engineering Design, Engineering Communications & CAD, Modeling & Analysis of Uncertainty
 
  - title: Organizations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Theta Xi Fraternity
        caption: Dec 2021 - Present
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Awards: George M. Baker Memorial Award (Apr 2024)
          - Positions Held: Scholarship Chairman (Apr 2023 - Dec 2023), Vice President / Risk Management Chairman (Dec 2022 - Apr 2023)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MIT App Inventor Punya AI Explainability
        caption: Jan 2024 - Present
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Master's Research Project, Dr. Oshani Seneviratne
        
      - layout: left
        title: Smart Dormitory - Node-RED
        caption: Aug 2023 - Dec 2023
        sub_title: Rensselaer Polytechnic Institute
        link: /files/Final%20Design%20Poster%20-%20Smart%20Dormitory%20-%20Node-RED.pdf
        link_text: Design Poster
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Multidisciplinary Capstone Design, Fall 2023, Dr. Dennis Shelden
          - Coordinated the enhancement of a low-code Smart Dormitory project which featured an IoT network of ESP32 devices with sensors connected through Arduino IDE and data visualizations powered by Node-RED
          - Integrated JavaScript and SQL to optimize query generation for MySQL database in order to efficiently retrieve historical sensor data and display on a website dashboard through graphs, charts, and heat maps
          - Executed strong project management skills through enhancements and coordinating the team's focus on scalability, energy efficiency, and security for students, building maintenance, and developers

      - layout: left
        title: SMART Pregnancy Band
        caption: Jun 2022 - Aug 2022
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Introduction to Engineering Design, Summer 2022, Dr. George Lee
          - Followed the engineering design process with a team of six students to develop a functional prototype for a SMART Pregnancy Band which featured a back-supporting band with medical sensors and mobile app compatibility
          - Led the team by working on the user interface subsystem by developing a mobile app that was built using MIT App Inventor 2 and intended to be used by pregnant women to track health data and prevent maternal deaths
          - The app featured nine screens with navigation bar and Bluetooth compatibility which was outlined in wireframe flow

      - layout: left
        title: Astro AutoTint
        caption: Jan 2022 - May 2022
        sub_title: Rensselaer Polytechnic Institute
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Electric Circuits, Spring 2022, Dr. Shayla Sawyer
          - Developed an Astro AutoTint electric circuit project in a team of three students that used a photoresistor to detect harmful light levels and adjust the shading of an electrochromic glass that could help astronauts in space
          - Utilized LTspice to create circuit schematics and Microsoft Word to develop a project manual demonstrating circuit concepts such as voltage followers, summers, comparators, inverting amplifiers, differentiators, and filters
          - Built and tested physical circuits using a breadboard, wires, operational amplifiers, power lines, and AC power


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
